/scan:
  reliability: best_effort
  durability: volatile
  history: keep_last
  depth: 10
/tf:
  reliability: best_effort
  durability: volatile
  history: keep_last
  depth: 100
/tf_static:
  reliability: reliable
  durability: transient_local
  history: keep_last
  depth: 100
odom:
  reliability: reliable
  durability: volatile
  history: keep_last
  depth: 10
/gazebo/model_states:
  reliability: best_effort
  durability: volatile
  history: keep_last
  depth: 10
